/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.UUID;

public class App {


    public static void main(String[] args) {
        System.out.println("Running Train Booking System");
        Scanner scanner = new Scanner(System.in);
        int option = 0;

        UserBookingService userBookingService;
        try{
            userBookingService = new UserBookingService();
        }catch(IOException e){
            System.out.println("There is something wrong");
            return;
        }

        while(option!=7){
            System.out.println("Choose Option");
            System.out.println("1. Sign Up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Booking");
            System.out.println("4. Search Train");
            System.out.println("5. Book a Service");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");
            option = scanner.nextInt();

            switch (option){
                case 1:
                    System.out.println("Enter Username to Signup");
                    String nameToSignup = scanner.next();
                    System.out.println("Enter the password to Signup");
                    String passwordToSignup = scanner.next();

                    User userToSignup = new User(nameToSignup,passwordToSignup, UserServiceUtil.hashedPassword(passwordToSignup), UUID.randomUUID().toString(),new ArrayList<>());
                    userBookingService.signUp(userToSignup);
                    break;
                case 2:
                    System.out.println("Enter username to Login");
                    String nameToLogin = scanner.next();
                    System.out.println("Enter password to Login");
                    String passwordToLogin = scanner.next();

                    User userToLogin = new User(nameToLogin,passwordToLogin, UserServiceUtil.hashedPassword(passwordToLogin), UUID.randomUUID().toString(),new ArrayList<>());

                    try{
                        userBookingService = new UserBookingService(userToLogin);
                    }catch(IOException e){
                        return;
                    }
                    break;
                case 3:
                    System.out.println("Fetching your bookings");
                    userBookingService.fetchBooking();
                    break;
                case 4:
                    
            }
        }
    }
}
